export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Gallery } from './Gallery'
export { default as Map } from './Map'
export { default as Contact } from './Contact'